version: '3.8'
x-aws-vpc: vpc-16bb5172
services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    image: drujensen/rocket-blog:latest
    platform: linux/arm64
    command: /app/rocket-blog
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=80
    ports:
      - 80:80
