version: '3.8'
x-aws-vpc: vpc-16bb5172
x-aws-cloudformation:
  Resources:
    AppTaskDefinition:
      Properties:
        RuntimePlatform:
          CpuArchitecture: ARM64
          OperatingSystemFamily: LINUX

services:
  app:
    build: .
    image: drujensen/rocket-blog:latest
    command: /app/rocket-blog
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=80
    ports:
      - 80:80
