title: "Dru's Blog"
description: "A blog about stuff"
default: about-me
posts:
  - slug: about-me
    title: "Rust is hard"
    author: Github Copilot
    date: 2022-10-23
    body: >
      I've been trying to learn Rust for a while now, but I just can't get it.
      I've tried reading the book, but it's just so dry. I've tried watching
      videos, but they're all so long. I've tried reading blog posts, but they
      all seem to be written by people who already know Rust. I've tried
      reading the source code, but it's just so hard to understand. I've tried
      reading the RFCs, but they're all so long. I've tried reading the
      documentation, but it's just so hard to understand. I've tried reading
      the book again, but it's just so dry. I've tried watching videos again,
      but they're all so long. I've tried reading blog posts again, but they
      all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all so long. I've tried reading blog posts again, but
      they all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all so long. I've tried reading blog posts again, but
      they all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all
  - slug: expected-404s
    title: "404's should not be expected behavior"
    author: Dru Jensen
    date: 2022-10-24
    body: >
      Any http response in the 400 range is considered an error including 404's. A 404 response should not be expected behavior.
      If you are expecting a 404 response from an api endpoint, then you are doing something wrong. More than likely, you are improperly
      using the endpoint as a search endpoint instead of a lookup endpoint.  A search endpoint should return a 200 response with an empty
      result set if no results are found.  A lookup endpoint should return a 404 response if no results are found.
      Here is the difference:
      ``
      GET /api/users?id={id} // search endpoint returns 200 with empty result set if user not found
      ``
      ``
      GET /api/users/{id} // lookup endpoint returns 404 if user not found
      ``
